<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-23T07:27:41Z" name="Default suite" finished-at="2024-01-23T07:28:00Z" duration-ms="18837">
    <groups>
    </groups>
    <test started-at="2024-01-23T07:27:41Z" name="Default test" finished-at="2024-01-23T07:28:00Z" duration-ms="18837">
      <class name="Serien.SerienLive.EndToEndTestCase">
        <test-method is-config="true" signature="lunchApplication()[pri:0, instance:Serien.SerienLive.EndToEndTestCase@27216cd]" started-at="2024-01-23T07:27:41Z" name="lunchApplication" finished-at="2024-01-23T07:27:44Z" duration-ms="2946" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchApplication -->
        <test-method signature="FromAdminPanleExpireTheSubscription(java.util.HashMap)[pri:0, instance:Serien.SerienLive.EndToEndTestCase@27216cd]" started-at="2024-01-23T07:27:44Z" name="FromAdminPanleExpireTheSubscription" data-provider="getdata2" finished-at="2024-01-23T07:28:00Z" duration-ms="15868" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{GroupName=TCS755Group1, CourseName=automatiom Test Training, =, quiz1Ans2=Three colleagues go to a cafe for a weekend brunch. One of them is verbally harassed by the staff of the restaurant., cerLink=//storage.googleapis.com/serein-devqa-internal-gcp.appspot.com/generatedCertificate/, empComCourses=1, companyName=TCS755, empNotComCourses=0, quiz1Ans1=Priya can reach out to both her company’s IC or the client's IC based on her comfort., startdate=23-01-2024, enrollmentDueDate=30-12-2024, Useremail=omkar@krishworks.com, Adminuserpass=pass2023, expectedExpText=Subscription Expired, enddate=30-12-2024, typeOfTraining=course, quiz2Ans1=The impact of Gaurav’s behaviour on Nisha is certainly more relevant here., totalEmp=1, userpass=password, empName=omkar123456, AdminUseremail=admin@demo.com, noticeperiod=10, groupExpDate=30-12-2024}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at Serien.SerienLive.EndToEndTestCase.FromAdminPanleExpireTheSubscription(EndToEndTestCase.java:104)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FromAdminPanleExpireTheSubscription -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Serien.SerienLive.EndToEndTestCase@27216cd]" started-at="2024-01-23T07:28:00Z" name="tearDown" finished-at="2024-01-23T07:28:00Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Serien.SerienLive.EndToEndTestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
